global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

# (Optional) Log information
# ---
# log:
#  level: ERROR  # DEBUG, INFO, WARNING, ERROR, CRITICAL
#   format: common  # common, json, logfmt
#   filePath: /var/log/traefik/traefik.log

# (Optional) Accesslog
# ---
# accesslog:
  # format: common  # common, json, logfmt
  # filePath: /var/log/traefik/access.log

api:
  dashboard: true
  insecure: true

# Entry Points configuration
# ---
entryPoints:
  web:
    address: :80

  websecure:
    address: :443

certificatesResolvers:
  staging:
    acme:
      email: rehabilita@rehabilita.com.br
      storage: /etc/ssl/certs/acme-staging.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

  production:
    acme:
      email: rehabilita@rehabilita.com.br
      storage: /etc/ssl/certs/acme-production.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

# (Optional) Overwrite Default Certificates
# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: /etc/traefik/certs/cert.pem
#         keyFile: /etc/traefik/certs/cert-key.pem

providers:
  docker:
    exposedByDefault: false  # Default is true
